jobs:
  include:
    - stage: "Build"
      language: java
      jdk:
        - openjdk8
      install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn test -P !build-extras -B
      cache:
        directories:
          - ~/.m2/repository
      after_success:
        - ./build/deploy.sh
    - stage: "Deploy Pages"
      language: node_js
      node_js:
        - lts/*
      install:
        - npm ci
      script:
        - npm run docs:build
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/.vuepress/dist
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
      if: commit_message !~ /\[skip-docs\].*/

