= OAS Generator
:author: Christian Horz
:icons: font


image:https://github.com/chhorz/oas-generator/workflows/Java%20CI/badge.svg?branch=master["Java CI",link=https://github.com/chhorz/oas-generator/actions?query=workflow%3A%22Java+CI%22]

== About
The *OAS Generator* is a java annotation processor that generates an OpenAPI specification file from the java annotations within the source code.
Because the file is generated during compilation, the documentation is always up to date and references the current state of the implementation.

* OpenAPI Specification 3.0.3 (link:https://spec.openapis.org/oas/v3.0.3[Link])

== Getting Started
. Add the corresponding dependency to your project
+
[source,xml]
----
<dependency>
    <groupId>com.github.chhorz</groupId>
    <artifactId>oas-generator-{spring-web|jaxrs|schema|asciidoctor}</artifactId>
    <version>0.1.0.RC2</version>
</dependency>
----
. Create a configuration file `oas-generator.yml` (per default in _/src/main/resources_).
An example can be found in the https://chhorz.github.io/oas-generator/documentation/reference.html[reference documentation].
. Update the Javadoc comments to match the requirements

== Documentation

The https://chhorz.github.io/oas-generator/[documentation] can be found on the separate Github Page.
The page also includes the https://chhorz.github.io/oas-generator/documentation/reference.html[reference documentation] for all versions.


== Snapshots
Snapshots are available from the Sonatype OSS Snapshots repository.
To configure the repository for your project to use the latest snapshot versions you have to add the following repository to your maven pom:
[source,xml]
----
<repositories>
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
----

== License
OAS Generator is Open Source software released under the link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].
