= OAS Generator
:author: Christian Horz
:icons: font

image:https://travis-ci.org/chhorz/oas-generator.svg?branch=master["Build Status", link="https://travis-ci.org/chhorz/oas-generator"]

== About
The *OAS Generator* is a java annotation processor that generates an OpenAPI specification file from the java annotations within the source code.
Because the file is generated during compilation, the documentation is always up to date and references the current state of the implementation.

== Documentation

The https://chhorz.github.io/oas-generator/[documentation] can be found on the separate Github Page.
The page also includes the https://chhorz.github.io/oas-generator/documentation/reference.html[reference documentation] for all versions.


== Snapshots
Snapshots are available from the Sonatype OSS Snapshots repository.
To configure the repository for your project to use the latest snapshot versions you have to add the following repository to your maven pom:
[source,xml]
----
<repositories>
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
----

== License
OAS Generator is Open Source software released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].
