= OAS Generator
:author: Christian Horz
:icons: font

image:https://github.com/chhorz/oas-generator/workflows/Java%20CI/badge.svg?branch=master["Java CI",link=https://github.com/chhorz/oas-generator/actions?query=workflow%3A%22Java+CI%22]
image:https://img.shields.io/maven-central/v/com.github.chhorz/oas-generator.svg?logo=apachemaven&label=Maven%20Central["Maven Central", link="https://search.maven.org/artifact/com.github.chhorz/oas-generator"]

== About
The *OAS Generator* is a java annotation processor that generates an OpenAPI specification file from the java annotations within the source code.
Because the file is generated during compilation, the documentation is always up-to-date and references the current state of the implementation.

* OpenAPI Specification 3.1.0 (link:https://spec.openapis.org/oas/v3.1.0[Link])

== Getting Started
. Add the corresponding dependency to your project
+
[source,xml]
----
<dependency>
    <groupId>com.github.chhorz</groupId>
    <artifactId>oas-generator-{spring-web|jaxrs|schema|asciidoctor}</artifactId>
    <version>${oas-generator.version}</version>
</dependency>
----
. Create a configuration file `oas-generator.yml` (per default in _/src/main/resources_).
An example can be found in the link:https://chhorz.github.io/oas-generator/docs/current/reference/configuration.html#configuration-file[reference documentation].
. Update the Javadoc comments to match the requirements

== Documentation

The link:https://chhorz.github.io/oas-generator/[documentation] can be found on the separate GitHub Page.
The page also includes the link:https://chhorz.github.io/oas-generator/docs/current/releases.html[reference documentation] for all versions.


== Snapshots
Snapshots are available from the Sonatype OSS Snapshots repository.
To configure the repository for your project to use the latest snapshot versions you have to add the following repository to your maven pom:
[source,xml]
----
<repositories>
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
----

== License
OAS Generator is Open Source software released under the link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].
