= OAS Generator
:author: Christian Horz
:icons: font
:revnumber: {project-version}
:source-highlighter: highlightjs
:docinfo: shared
:toc: left

== About
_tbd_

== Snapshots
_tbd_

== Configuration
The configuration of the _OAS Generator_ is primarily done with the <<configuration-file,configuration file>>.
Compiler options described below should be used to customize the name or path of the configuration file.

=== Compiler options
A basic set of configuration options can be done by compiler options.
Compiler options with the prefix `-A` will recognized by an annotation processor.
The following options can be used:

`propertiesPath`::
As default the configuration file is placed at `src/main/resources` and has the name `oas-generator.yml`.
The name or path can be changed by using this compiler option.
`schemaPath`::
If the resources/schemas are placed in a separate project or maven module, the Javadoc comments can not be parsed.
In this case the schemas can be parsed with the `oas-generator-schema` annotation processor.
To merge the schemas with the ones parsed with one of the other processors the path to the first generated file can be configured with this path.
`version`::
This option passes for example the current project version to the generated specification.

Not all compiler options are available in all annotation processors.
The following table explains the availability:

.Available compiler options per module
[cols="4"] 
|===
| Module
| `propertiesPath`
| `schemaPath`
| `version`

| _oas-generator-spring-web_
| icon:check[role="green"]
| icon:check[role="green"]
| icon:check[role="green"]

| _oas-generator-schema_
| icon:check[role="green"]
| icon:minus[role="red"]
| icon:minus[role="red"]
|===

[[configuration-file]]
=== Configuration file
The configuration file is splitted into two parts.
Both parts are in the same file (Default: _oas-generator.yml_).

.Content included in `openapi.json`
[source,yaml]
----
# Documentation information that will be included in openapi.json
info:
  title: MyService
  version: 1.2.3-SNAPSHOT
  contact:
    name: John Doe
    url: http://www.google.com
    email: john@doe.com
  license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

servers:
- url: dev.server.lan
  description: Internal DEV-Stage

externalDocs:
  url: http://www.wikipedia.org
  description: Lorem ipsum ...

securitySchemes:
  read_role:
    description: Basic LDAP read role.
    type: http
    scheme: basic

tags:
  order:
    description: The category collects all methods for orders.
    externalDocs:
      url: http://www.google.com
----

.Configuration to adjust the generator behavior
[source,yaml]
----
# Parser specific configuration
parser:
  logLevel: DEBUG
  outputDir: ./target/openapi
  outputFile: openapi.json
  schemaFile: api-module/target/openapi/openapi-schema.json
  schemaPackages:
  - com.github.chhorz.openapi.spring.test.controller.external
----

== License
OAS Generator is Open Source software released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].