= OAS Generator
:author: Christian Horz
:icons: font
:revnumber: {project-version}
:docinfo: shared-head
:toc: left
:toclevels: 3
:sectnums:
:sectlinks:
:sectanchors:
:source-highlighter: highlightjs
:highlightjs-theme: zenburn
:common-java: ../../../../oas-generator-common/src/main/java

== About
The *OAS Generator* is a java annotation processor that creates an OpenAPI specification during the build process.
It is based on static code analysis, especially annotations that are used to create a REST API.
Additional the JavaDoc comments from the given methods or resource objects will be included if they follow a defined format.

[source%nowrap,java]
----
@RequestMapping(path = "/orders")
public class OrderController {

    /**
    * Get an order with an {@code id}.
     *
     * @category order
     *
     * @param id
     *            the identifier
     * @param filter
     *            the filter that can be applied
     * @return a list of orders that match the optional filters
     */
    @GetMapping(value = "/{id:\\d+}", produces = { "application/json" })
    public List<Order> getOrder(
                @PathVariable Long id,
                @RequestParam(defaultValue = "valid=true",
                              required = false) String filter) {
        // implementation
    }

}
----

== Installation
In the following section possible options are shown in which way the *OAS Generator* can be included in your project.

[TIP]
====
The following examples use the `oas-generator-spring-web`.
Each kind of installation also works with the `oas-generator-jaxrs` or `oas-generator-schema` module.
====

=== Apache Maven

==== Include via dependency
The simplest way to add the *OAS Generator* to your project is adding the following dependency:
[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>com.github.chhorz</groupId>
    <artifactId>oas-generator-spring-web</artifactId>
    <version>{revnumber}</version>
    <scope>provided</scope> <!--1-->
</dependency>

<!-- Required if 'oas-generator-spring-web' or 'oas-generator-jaxrs' are of scope provided -->
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId> <!--2-->
    <scope>compile</scope>
</dependency>
----
<1> The _scope_ `provided` is useful, if you want to exclude the *OAS Generator* dependencies during runtime.
<2> This additional dependency is required for Spring-Boot applications because the `snakeyaml` dependency is declared of scope `runtime` within the spring boot starter dependency.

All dependencies contain additional information within the `META-INF` folder that define the dependency as annotation processor.

==== Maven compiler plugin
Another way to include an annotation processor is the link:https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html[maven-compiler-plugin]:
[source%nowrap,xml,subs="verbatim,attributes"]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <annotationProcessorPaths> <!--1-->
            <path>
                <groupId>com.github.chhorz</groupId>
                <artifactId>oas-generator-spring-web</artifactId>
                <version>{revnumber}</version>
            </path>
            <!-- ... more ... -->
        </annotationProcessorPaths>
        <annotationProcessors> <!--2-->
            <annotationProcessor>com.github.chhorz.openapi.spring.SpringWebOpenApiProcessor</annotationProcessor>
            <!-- ... more ... -->
        </annotationProcessors>
    </configuration>
</plugin>
----
<1> Plugin documentation: link:https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths[annotationProcessorPaths]
<2> Plugin documentation: link:https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessors[annotationProcessors]

It is not possible to mix this way of annotation processor integration with the dependency based one.

== Javadoc
In this section we describe the default structure of the Javadoc comments.
A common structure is required to get all data parsed correct.
This is necessary because Javadoc comments in general are unstructured comments and can be formatted in different ways.

This project uses the link:https://github.com/chhorz/javadoc-parser[Javadoc Parser] project to load all information from the Javadoc comments as structured data.

.Maven dependency for the Javadoc Parser:
[source,xml]
----
<dependency>
    <groupId>com.github.chhorz</groupId>
    <artifactId>javadoc-parser</artifactId>
    <version>${javadoc-parser.version}</version>
</dependency>
----

=== Supported tags
In general the method description and summary are extracted for all API methods.
The description is the complete text from the beginning of the Javadoc comment to the first Javadoc tag.
Additional the summary is, unless not marked with the `@summary` tag, the first sentence of the description.
Other included tags are:

* `@param` tag for a description of the method parameters and and so the API parameters
* `@return` for the semantic meaning of the response
* `@category` to represent OpenAPI tags

=== Custom javadoc tags
To render the custom javadoc tags properly within the HTML javadoc api documentation, the following configuration of the `maven-javadoc-plugin` has to be done:

.Configuration of `maven-javadoc-plugin`
[source,xml]
----
<configuration>
    <tags>
        <tag>
            <name>response</name>
            <placement>a</placement>
            <head>OpenAPI response:</head>
        </tag>
        <tag>
            <name>security</name>
            <placement>a</placement>
            <head>OpenAPI security scheme:</head>
        </tag>
    </tags>
</configuration>
----

==== Define responses
Because the different response codes and contents are defined within the method body, the *OAS Generator* is not capable of reading this information.
To specify the possible response status the `@response` javadoc tag could be used:

.Example Javadoc comment
[source,java]
----

/**
 * @response 200 SomeResource
 *                      the resource that will be returned
 * @response 404 ProblemResource
 *                      the generic problem resource for error case
 */
----

==== Security schemes
The *OAS Generator* reads information about the required security schemes form some _spring-security_ annotations (e.g. `@PreAuthorize`).
If none of these annotations is present on the API method, the security scheme can also be defined in the javadoc comment:

The content of the tag must match the name of a security requirement from the `oas-generator.yml` file.

.Example Javadoc comment
[source,java]
----

/**
 * @security read_role
 */
----


== Configuration
The configuration of the _OAS Generator_ is primarily done with the <<configuration-file,configuration file>>.
Compiler options described below could be used to customize the name or path of the configuration file.

[[compiler_options]]
=== Compiler options
A basic set of configuration options can be done by compiler options.
Compiler options with the prefix `-A` will be recognized by an annotation processor.
The following options can be used:

`propertiesPath`::
As default the configuration file is placed at `src/main/resources` and has the name `oas-generator.yml`.
The name or path can be changed by using this compiler option.
`schemaPath`::
If the resources/schemas are placed in a separate project or maven module, the Javadoc comments can not be parsed.
In this case the schemas can be parsed with the `oas-generator-schema` annotation processor.
To merge the schemas with the ones parsed with one of the other processors the path to the first generated file can be configured with this path.
`version`::
This option passes for example the current project version to the generated specification.

Not all compiler options are available in all annotation processors.
The following table explains the availability:

.Available compiler options per module
[cols="4"] 
|===
| Module
| `propertiesPath`
| `schemaPath`
| `version`

| _oas-generator-spring-web_
| icon:check[role="green"]
| icon:check[role="green"]
| icon:check[role="green"]

| _oas-generator-jaxrs_
| icon:check[role="green"]
| icon:check[role="green"]
| icon:check[role="green"]

| _oas-generator-schema_
| icon:check[role="green"]
| icon:minus[role="red"]
| icon:minus[role="red"]
|===

==== Maven Compiler Plugin
To configure the options above with the `maven-compile-plugin` the following configuration has to be added to the plugin:
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <compilerArgs>
            <arg>-Aversion=${project.version}</arg>
        </compilerArgs>
    </configuration>
</plugin>
----

[[configuration-file]]
=== Configuration file
The configuration file is split into two parts.
Both parts are content of the same file (Default: _oas-generator.yml_ within the classpath).

.Minimal `oas-generator.yml` configuration file
[source,yaml]
----
info:
  title: MyService
  version: 1.2.3-SNAPSHOT #<1>
----
<1> Can be removed if provided as <<compiler_options,compiler option>>

Full description of the possible values is shown below:

.Content included in `openapi.json`
[source,yml]
----
# Documentation information that will be included in openapi.json
info:
  title: MyService # REQUIRED
  version: 1.2.3-SNAPSHOT # REQUIRED <1>
  contact:
    name: John Doe
    url: https://www.google.com
    email: john@doe.com
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: dev01.server.lan
    description: Internal DEV-Stage 1
    variables: &server_variables #<2>
      port:
        enumValues:
          - 8080
          - 443
        defaultValue: "443"
        description: The port of the application
  - url: dev02.server.lan
    description: Internal DEV-Stage 2
    variables: *server_variables #<2>

externalDocs:
  url: https://www.openapis.org/
  description: Lorem ipsum ...

securitySchemes:
  read_role:
    description: Basic LDAP read role.
    type: http
    scheme: basic

tags:
  tag_name:
    description: The category collects all methods for orders.
    externalDocs:
      url: https://www.google.com
----
<1> The Version can be set fix within the configuration file.
Otherwise the configuration file can be filtered by maven for example.
The version has to be replaced with an variable for the maven project version: `@project.version@`.
+
.Maven example for filtering
[source,xml]
----
<project>
  ...
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
      ...
    </resources>
    ...
  </build>
  ...
</project>
----
<2> YAML references can be used to remove redundant parts of the configuration.

The content of the part above will be included in the resulting OpenAPI document as it is defined.
It is static content that will not change often, so it should be defined as static data.
Only data that could not be retrieved from the source code and is required by the OpenAPI specification must be present in the shown file.

Parser properties shown below customize the behavior of the *OAS Generator*:

.Configuration to adjust the generator behavior
[source,yaml]
----
# Parser specific configuration
parser:
  logLevel: DEBUG # DEBUG, INFO, ERROR
  outputDir: ./target/openapi # <1>
  outputFile: openapi # <1>
  outputFormay: json,yaml
  schemaDir: ./target/openapi
  schemaFile: api-module/target/openapi/openapi-schema.json # <2>
  schemaPackages:
    - com.github.chhorz.openapi.spring.test.controller.external # <2>
  postProcessor: # <3>
    postProcessor1:
      key1: value1
      key2: value2
    postProcessor2:
      key1: value1
----
<1> Output path and filename of the generated OpenAPI specification file
<2> Path to previously generate schema files - _(Optional)_
<3> Key-Value maps for custom post processors, e.g. <<asciidoctor.properties,asciidoctor postprocessor>> -  _(Optional)_

The `postProcessor` properties define a generic list of properties.
In this map contributors can define their own properties for their post processors using the provided spi.

== Extensibility
The *OAS Generator* provides a service provider interface (SPI) to include custom post processors.
Currently, the following post processors (see module link:https://github.com/chhorz/oas-generator/tree/master/oas-generator-spi[_oas-generator-spi_]) are provided:

- `FileWriterPostProcessor`
- `AsciidoctorPostProcessor`

If other post processors should be listed and added in the *OAS Generator* repo please open a Github issue.

=== Post-Processor Documentation
In the following section all post processors from the `oas-generator-spi` module are documented.

==== FileWriterPostProcessor
The `FileWriterPostProcessor` is used internally to write the OpenAPI domain model to the resulting output file.
This Post-Processor is included within all *OAS Generator* modules and must not be included with adn additional dependency.

==== AsciidoctorPostProcessor
This post processor converts the generated OpenAPI domain model into the asciidoctor format.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>com.github.chhorz</groupId>
    <artifactId>oas-generator-asciidoctor</artifactId>
    <version>{revnumber}</version>
    <scope>provided</scope>
</dependency>
----

After the creation during the compile phase, the `asciidoctor-maven-plugin` (link:https://asciidoctor.org/docs/asciidoctor-maven-plugin/[Link]) can be used to render the `.adoc` file to HTML, PDF or other formats

[[asciidoctor.properties]]
===== Configuration properties
All the following properties will be defined as key-value list in the <<configuration-file, configuration file>>.

.Configuration with default values
[source,yaml]
----
parser:
  postProcessor:
    asciidoctor:
      logging: true
      templateLocalizedLookup: false
      templatePath: ./templates/freemarker # <1>
      templateFile: openapi.ftlh
      outputPath: ./target/openapi # <2>
      outputFile: /openapi.adoc
      standaloneFile: true # <3>
----
<1> The path of the templates is based on `/src/main/resources`
<2> Output base directory is the `/target/openapi` folder
<3> A standalone file is generated with an asciidoctor document header and a section title on level 0.
Files generated with `false` can easier integrated in other asciidoctor files.

The conversion of the internal openapi domain object into a asciidoctor file is done via the link:https://freemarker.apache.org/[Apache FreeMarker] template engine.
Some of the configuration properties shown above are related to this engine.

=== Custom Post-Processors
Providing your own post processor is very simple.
You just have to follow these steps:

. Implement the `PostProcessorProvider` interface to create a custom post processor
+
[source,java]
----
include::{common-java}/com/github/chhorz/openapi/common/spi/PostProcessorProvider.java[]
----
. Implement the `OpenAPIPostProcessor` interface with the actual execution method
+
[source,java]
----
include::{common-java}/com/github/chhorz/openapi/common/spi/OpenAPIPostProcessor.java[]
----
. Create a file named `com.github.chhorz.openapi.common.spi.PostProcessorProvider` at `src/main/resources/META-INF/services` containing the fully qualified name of the class from step 1
+
.Directory structure
[source]
----
/src
  /main
    /resources
      /META-INF
        /services
          com.github.chhorz.openapi.common.spi.PostProcessorProvider
----
+
.File content is the full name of the custom post processor. (Example for `AsciidoctorProvider.java`)
[source]
----
com.github.chhorz.openapi.spi.asciidoctor.AsciidoctorProvider
----

. If the post processor uses custom properties these should be placed below the parser properties as shown for the <<asciidoctor.properties, Asciidoctor Post Processor>>.
All custom property classes should extend the provided `AbstractPostProcessorProperties` class.

== Limitations

There are some limitations based on the underlying concept of java annotation processors.
These annotation processors are processing the abstract syntax tree of the java classes.

* Annotation processors have no information about the method body.
Only the method signature and the documentation comment (javadoc comment) are available.
If you choose a different return object or status code during runtime you have to document this information on a place that is available at compile time.
Either the documentation comments or other annotations should be used in this place.

== Snapshots
Snapshots are available from the Sonatype OSS Snapshots repository.
To configure the repository for your project to use the latest snapshot versions you have to add the following repository to your maven pom:
[source,xml]
----
<repositories>
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
----

== License
OAS Generator is Open Source software released under the link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].
