= OAS Generator
:author: Christian Horz
:icons: font
:revnumber: {project-version}
:source-highlighter: highlightjs
:docinfo: shared
:toc: left
:common-java: ../../../../oas-generator-common/src/main/java

== About
_tbd_

== Javadoc
In this section we describe the default structure of the Javadoc comments.
A common structure is needed to get all data parsed correct.
This is necessary because Javadoc comments in general are unstructured comments and can be formatted in different ways.

== Configuration
The configuration of the _OAS Generator_ is primarily done with the <<configuration-file,configuration file>>.
Compiler options described below should be used to customize the name or path of the configuration file.

=== Compiler options
A basic set of configuration options can be done by compiler options.
Compiler options with the prefix `-A` will recognized by an annotation processor.
The following options can be used:

`propertiesPath`::
As default the configuration file is placed at `src/main/resources` and has the name `oas-generator.yml`.
The name or path can be changed by using this compiler option.
`schemaPath`::
If the resources/schemas are placed in a separate project or maven module, the Javadoc comments can not be parsed.
In this case the schemas can be parsed with the `oas-generator-schema` annotation processor.
To merge the schemas with the ones parsed with one of the other processors the path to the first generated file can be configured with this path.
`version`::
This option passes for example the current project version to the generated specification.

Not all compiler options are available in all annotation processors.
The following table explains the availability:

.Available compiler options per module
[cols="4"] 
|===
| Module
| `propertiesPath`
| `schemaPath`
| `version`

| _oas-generator-spring-web_
| icon:check[role="green"]
| icon:check[role="green"]
| icon:check[role="green"]

| _oas-generator-jaxrs_
| icon:check[role="green"]
| icon:check[role="green"]
| icon:check[role="green"]

| _oas-generator-schema_
| icon:check[role="green"]
| icon:minus[role="red"]
| icon:minus[role="red"]
|===

[[configuration-file]]
=== Configuration file
The configuration file is split into two parts.
Both parts are in the same file (Default: _oas-generator.yml_).

.Content included in `openapi.json`
[source,yaml]
----
# Documentation information that will be included in openapi.json
info:
  title: MyService
  version: 1.2.3-SNAPSHOT
  contact:
    name: John Doe
    url: http://www.google.com
    email: john@doe.com
  license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

servers:
- url: dev.server.lan
  description: Internal DEV-Stage

externalDocs:
  url: http://www.wikipedia.org
  description: Lorem ipsum ...

securitySchemes:
  read_role:
    description: Basic LDAP read role.
    type: http
    scheme: basic

tags:
  order:
    description: The category collects all methods for orders.
    externalDocs:
      url: http://www.google.com
----

The content of the part above will be included in the resulting OpenAPI document as it was defined.
Parser properties shown below customize the behavior of the _oas-generator_:

.Configuration to adjust the generator behavior
[source,yaml]
----
# Parser specific configuration
parser:
  logLevel: DEBUG
  outputDir: ./target/openapi
  outputFile: openapi.json
  schemaFile: api-module/target/openapi/openapi-schema.json
  schemaPackages:
  - com.github.chhorz.openapi.spring.test.controller.external
  postProcessor:
    key1: value1
    key2: value2
----

The `postProcessor` properties define a generic list of properties.
In this map contributors can define their own properties for their post processors using the provided spi.

== Extensibility
The OAS Generator provides a service provider interface (SPI) to include custom post processors.
Per default the `FileWriterPostProcessor` is included to write the _openapi.json_ file.
Currently the following post processors (see module _oas-generator-spi_) are also provided:

- `AsciidoctorPostProcessor`

=== Implementation
Providing your own post processor is very simple.
You just have to follow these steps:

. Implement the `PostProcessorProvider` interface to create a custom post processor
+
[source,java]
----
include::{common-java}/com/github/chhorz/openapi/common/spi/PostProcessorProvider.java[]
----
. Implement the `OpenAPIPostProcessor` interface with the actual execution method
+
[source,java]
----
include::{common-java}/com/github/chhorz/openapi/common/spi/OpenAPIPostProcessor.java[]
----
. Create a file named `com.github.chhorz.openapi.common.spi.PostProcessorProvider` at `src/main/resources/META-INF/services` containing the fully qualified name of the class from step 1

== Snapshots
_tbd_

== License
OAS Generator is Open Source software released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].