= OAS Generator
:author: Christian Horz
:icons: font
:revnumber: {project-version}
:source-highlighter: highlightjs
:highlightjsdir: highlight
:highlightjs-theme: obsidian
// :docinfo: shared
:toc: left
:sectnums:
:sectlinks:
:sectanchors:
:toclevels: 3
:common-java: ../../../../oas-generator-common/src/main/java

== About
The *OAS Generator* is a java annotation processor that creates an openapi specification during the build process.
It is based on static code analysis, especially annotations that are used to create a REST API.
Additional the JavaDoc comments from the given methods or resource objects will be included.

[source%nowrap,java]
----
@RequestMapping(path = "/orders")
public class OrderController {

	/**
	 * Get an order with an {@code id}.
	 *
	 * @category order
	 *
	 * @param id
	 *            the identifier
	 * @param filter
	 *            the filter that can be applied
	 * @return a list of orders that match the optional filters
	 */
	@GetMapping(value = "/{id:\\d+}", produces = { "application/json" })
	public List<Order> getOrder(
                @PathVariable Long id,
                @RequestParam(defaultValue = "valid=true", required = false) String filter) {
	    // implementation
	}
----

== Installation
In the following section possible options are shown in which way the *OAS Generator* can be included in your project.

[TIP]
The following examples use the `oas-generator-spring-web`.
Each kind of installation also works with the `oas-generator-jaxrs` or `oas-generator-schema` module.

=== Apache Maven

==== Include via dependency
The simplest way to add the *OAS Generator* to your project is adding the following dependency:
[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>com.github.chhorz</groupId>
    <artifactId>oas-generator-spring-web</artifactId>
    <version>{revnumber}</version>
</dependency>
----
All dependencies contain some `META-INF` information which define the provided annotation processors.

==== Maven compile plugin
Another way to include an annotation processor is the link:https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html[maven-compiler-plugin]:
[source%nowrap,xml,subs="verbatim,attributes"]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <annotationProcessorPaths> <!--1-->
            <path>
                <groupId>com.github.chhorz</groupId>
                <artifactId>oas-generator-spring-web</artifactId>
                <version>{revnumber}</version>
            </path>
            <!-- ... more ... -->
        </annotationProcessorPaths>
        <annotationProcessors> <!--2-->
            <annotationProcessor>com.github.chhorz.openapi.spring.SpringWebOpenApiProcessor</annotationProcessor>
            <!-- ... more ... -->
        </annotationProcessors>
    </configuration>
</plugin>
----
<1> Plugin documentation: link:https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths[annotationProcessorPaths]
<2> Plugin documentation: link:https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessors[annotationProcessors]

It is not possible to mix this way of annotation processor integration with the dependency based one.

== Javadoc
In this section we describe the default structure of the Javadoc comments.
A common structure is needed to get all data parsed correct.
This is necessary because Javadoc comments in general are unstructured comments and can be formatted in different ways.

== Configuration
The configuration of the _OAS Generator_ is primarily done with the <<configuration-file,configuration file>>.
Compiler options described below should be used to customize the name or path of the configuration file.

=== Compiler options
A basic set of configuration options can be done by compiler options.
Compiler options with the prefix `-A` will recognized by an annotation processor.
The following options can be used:

`propertiesPath`::
As default the configuration file is placed at `src/main/resources` and has the name `oas-generator.yml`.
The name or path can be changed by using this compiler option.
`schemaPath`::
If the resources/schemas are placed in a separate project or maven module, the Javadoc comments can not be parsed.
In this case the schemas can be parsed with the `oas-generator-schema` annotation processor.
To merge the schemas with the ones parsed with one of the other processors the path to the first generated file can be configured with this path.
`version`::
This option passes for example the current project version to the generated specification.

Not all compiler options are available in all annotation processors.
The following table explains the availability:

.Available compiler options per module
[cols="4"] 
|===
| Module
| `propertiesPath`
| `schemaPath`
| `version`

| _oas-generator-spring-web_
| icon:check[role="green"]
| icon:check[role="green"]
| icon:check[role="green"]

| _oas-generator-jaxrs_
| icon:check[role="green"]
| icon:check[role="green"]
| icon:check[role="green"]

| _oas-generator-schema_
| icon:check[role="green"]
| icon:minus[role="red"]
| icon:minus[role="red"]
|===

[[configuration-file]]
=== Configuration file
The configuration file is split into two parts.
Both parts are in the same file (Default: _oas-generator.yml_).

.Content included in `openapi.json`
[source,yaml]
----
# Documentation information that will be included in openapi.json
info:
  title: MyService
  version: 1.2.3-SNAPSHOT
  contact:
    name: John Doe
    url: http://www.google.com
    email: john@doe.com
  license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

servers:
- url: dev.server.lan
  description: Internal DEV-Stage

externalDocs:
  url: http://www.wikipedia.org
  description: Lorem ipsum ...

securitySchemes:
  read_role:
    description: Basic LDAP read role.
    type: http
    scheme: basic

tags:
  order:
    description: The category collects all methods for orders.
    externalDocs:
      url: http://www.google.com
----

The content of the part above will be included in the resulting OpenAPI document as it was defined.
Parser properties shown below customize the behavior of the _oas-generator_:

.Configuration to adjust the generator behavior
[source,yaml]
----
# Parser specific configuration
parser:
  logLevel: DEBUG
  outputDir: ./target/openapi
  outputFile: openapi.json
  schemaFile: api-module/target/openapi/openapi-schema.json
  schemaPackages:
  - com.github.chhorz.openapi.spring.test.controller.external
  postProcessor:
    key1: value1
    key2: value2
----

The `postProcessor` properties define a generic list of properties.
In this map contributors can define their own properties for their post processors using the provided spi.

== Extensibility
The OAS Generator provides a service provider interface (SPI) to include custom post processors.
Per default the `FileWriterPostProcessor` is included to write the _openapi.json_ file.
Currently the following post processors (see module _oas-generator-spi_) are also provided:

- `AsciidoctorPostProcessor`

If other post processors should be listed and added in the *OAS Generator* repo please open a Github issue.

=== Post-Processor Documentation
In the following section all post processors from the `oas-generator-spi` module are documented.

==== AsciidoctorPostProcessor
This post processor converts the generated OpenAPI domain model into the asciidoctor format.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
	<groupId>com.github.chhorz</groupId>
	<artifactId>oas-generator-asciidoctor</artifactId>
	<version>{revnumber}</version>
</dependency>
----

After the creation during the compile phase, the `asciidoctor-maven-plugin` (link:https://asciidoctor.org/docs/asciidoctor-maven-plugin/[Link]) can be used to render the `.adoc` file to HTML, PDF or other formats

===== Configuration properties
All of the following properties are passed as key-value list in the <<configuration-file, configuration file>>.

.Configuration with default values
[source,yaml]
----
parser:
  postProcessor:
    asciidoctor.logging: true
    asciidoctor.template.localizedLookup: false
    asciidoctor.template.folder: /templates/freemarker # <1>
    asciidoctor.template.name: openapi.ftlh
    asciidoctor.output.dir: /openapi # <2>
    asciidoctor.output.file: /openapi.adoc
    asciidoctor.standlone.file: true # <3>
----
<1> The path of the templates is based on `/src/main/resources`
<2> Output base directory is the `/target` folder
<3> A standalone file is generated with an asciidoctor document header and a section title on level 0.
Files generated with `false` can easier integrated in other asciidoctor files.

=== Custom Post-Processors
Providing your own post processor is very simple.
You just have to follow these steps:

. Implement the `PostProcessorProvider` interface to create a custom post processor
+
[source,java]
----
include::{common-java}/com/github/chhorz/openapi/common/spi/PostProcessorProvider.java[]
----
. Implement the `OpenAPIPostProcessor` interface with the actual execution method
+
[source,java]
----
include::{common-java}/com/github/chhorz/openapi/common/spi/OpenAPIPostProcessor.java[]
----
. Create a file named `com.github.chhorz.openapi.common.spi.PostProcessorProvider` at `src/main/resources/META-INF/services` containing the fully qualified name of the class from step 1

== Snapshots
Snapshots are available from the Sonatype OSS Snapshots repository.
To configure the repository for your project to use the latest snapshot versions you have to add the following repository to your maven pom:
[source,xml]
----
<repositories>
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
----

== License
OAS Generator is Open Source software released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[Apache 2.0 license].