name: 'GitHub Pages'

on:
  push:
    paths: 
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'
    branches:
      - master

jobs:
  build-deploy:
    name: 'Build and deploy GitHub Page'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run docs:build

      - name: 'Deploy'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist
          publish_branch: gh-pages
