name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against LTS and current version:
        java: [ 8, 11, 14 ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set up JDK 
      uses: actions/setup-java@v1
      with:
        java-package: jdk
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn package --file pom.xml
