name: 'Java CI'

on: [push, pull_request]

env:
  OSSRH_JIRA_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  OSSRH_JIRA_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  test:
    name: 'Build and test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against LTS version:
        java: [ 8, 11 ]
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2

    - name: 'Set up JDK'
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: ${{ matrix.java }}

    - name: 'Cache local Maven repository'
      uses: actions/cache@v2.1.5
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: 'Build with Maven'
      run: ./mvnw -V -B --no-transfer-progress install

  publish-snapshot:
    name: 'Publish snapshot'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: 8
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: 'Cache local Maven repository'
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 'Publish snapshot'
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'chhorz/oas-generator'
        run: ./mvnw -B clean deploy --no-transfer-progress -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
